# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy NuGet package

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
    - name: Pack Nuget
      run: dotnet pack --configuration Release
    - name: Deploy
      run: 
        dotnet nuget add source --username USERNAME --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/DarkFactorAS/index.json"
        dotnet nuget push "bin/Release/*.nupkg"  --api-key ${{ secrets.NUGET_TOKEN }} --source "github"
